version: '3'
services:
    sortinghat-db:
        container_name: sortinghat-db
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=sortinghat
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
        expose:
            - 5432
        logging:
            driver: json-file
        networks:
          - sortinghat-network
    sortinghat-app:
        depends_on:
            - sortinghat-db
        container_name: sortinghat-app
        build:
            context: ./
        image: sorting-hat:latest
        entrypoint: /opt/sorting-hat/bin/sorting-hat-entrypoint.sh
        ports:
            - 8080:8080
        expose:
            - 8080
        environment:
            - "SPRING_PROFILES_ACTIVE=prod"
        logging:
            driver: json-file
        networks:
          - sortinghat-network
networks:
    sortinghat-network:
        driver: bridge
