insert into casa values
(1, 'Grifinória', 'Sua morada é a Grifinória! Casa onde habitam os corações indômitos. Ousadia, sangue-frio e nobreza destacam os alunos da Grifinória dos demais.'),
(2, 'Lufa-Lufa', 'É na Lufa-Lufa que você vai morar! Onde seus moradores são justos, leais, pacientes, sinceros, sem medo da dor.'),
(3, 'Corvinal', 'Será a velha e sábia Corvinal, A casa dos que tem a mente sempre alerta, onde os homens de grande espírito e saber sempre encontrarão companheiros seus iguais.'),
(4, 'Sonserina', 'A Sonserina será a sua casa! E ali fará seus verdadeiros amigo. Homens de astúcia que usam quaisquer meios para atingir os fins que antes colimaram.'),
(5, 'Professores', 'Nós, professores, somos muito bons em magia, sabe.');

insert into aluno (email, id_casa, nome) values
 ('lucas.suppes@bridge.ufsc.br',1, 'Lucas Suppes'),
 ('salomao@bridge.ufsc.br',1, 'Salomão Rodrigues'),
 ('leonardo.phildeg@bridge.ufsc.br',1, 'Leonardo Degering'),
 ('amanda.aquino@bridge.ufsc.br',1, 'Amanda Aquino'),
 ('joaomiguel@bridge.ufsc.br',1, 'João Miguel'),
 ('renan@bridge.ufsc.br',1, 'Renan Arceno'),
 ('jessica@bridge.ufsc.br',1, 'Jessica Xafranski'),
 ('candinho@bridge.ufsc.br',1, 'Candinho Junior'),
 ('delrobson@bridge.ufsc.br',1, 'Delrobson Valente'),
 ('celio@bridge.ufsc.br',1, 'Celio Cunha'),
 ('carlosrebelato@bridge.ufsc.br',1, 'Carlos Rebelato'),
 ('saldanha@bridge.ufsc.br',1, 'Gabriel Saldanha'),
 ('fernanda.mioto@bridge.ufsc.br',1, 'Fernanda Mioto'),
 ('ricardo@bridge.ufsc.br',1, 'Ricardo Prado'),
 ('fernando@bridge.ufsc.br',1, 'Fernando Gonçalves'),
 ('leticia@bridge.ufsc.br',1, 'Letícia Marques'),
 ('angelo@bridge.ufsc.br',1, 'Angelo Leal'),
 ('gessica@bridge.ufsc.br',1, 'Gessica Lehmkuhl'),
 ('nathanwerlich@bridge.ufsc.br',1, 'Nathan Werlich'),
 ('chris@bridge.ufsc.br',2, 'Christian Pieri'),
 ('monique@bridge.ufsc.br',2, 'Monique Bertan'),
 ('geovana@bridge.ufsc.br',2, 'Geovana Lima'),
 ('camila@bridge.ufsc.br',2, 'Camila Maia'),
 ('petroski@bridge.ufsc.br',2, 'Lucas Petroski'),
 ('luis.munoz@bridge.ufsc.br',2, 'Luis Muñoz'),
 ('rahony@bridge.ufsc.br',2, 'Rahony Goulart'),
 ('otavioribeiro@bridge.ufsc.br',2, 'Otávio Ribeiro'),
 ('silvia@bridge.ufsc.br',2, 'Silvia Laurentino' ),
 ('fabiopreisler@bridge.ufsc.br',2, 'Fabio Preisier' ),
 ('deborawernke@bridge.ufsc.br',2, 'Débora Wernke' ),
 ('gustavolobo@bridge.ufsc.br',2, 'Gustavo Lobo' ),
 ('ana.elisa@bridge.ufsc.br',2, 'Ana Kruger'),
 ('ja.pierry@bridge.ufsc.br',2, 'Jan Pierry'),
 ('lucas.joao@bridge.ufsc.br',2, 'Lucas João'),
 ('isaac@bridge.ufsc.br',2, 'Isaac Luiz'),
 ('allan@bridge.ufsc.br',2, 'Allan Ferreira'),
 ('jobe@bridge.ufsc.br',2, 'Jobe Michel'),
 ('leonardoschluter@bridge.ufsc.br',2, 'Leonardo Schluter'),
 ('gustavomoser@bridge.ufsc.br',3, 'Gustavo Moser'),
 ('bruno.luiz@bridge.ufsc.br',3, 'Bruno Luiz' ),
 ('burigo@bridge.ufsc.br',3, 'Fernando Burigo'),
 ('ewerton@bridge.ufsc.br',3, 'Ewerton Conceição'),
 ('wag@bridge.ufsc.br',3, 'Wagner Braga'),
 ('rafael@bridge.ufsc.br',3, 'Rafael Barbaresco' ),
 ('anna.victoria@bridge.ufsc.br',3, 'Anna Victoria'),
 ('isabellepinheiro@bridge.ufsc.br',3, 'Isabelle Pinheiro' ),
 ('larissataw@bridge.ufsc.br',3, 'Larissa Taw'),
 ('marcel@bridge.ufsc.br',3, 'Marcel Figueiredo'),
 ('christian@bridge.ufsc.br',3, 'Christian Martins'),
 ('nathalia.lucca@bridge.ufsc.br',3, 'Nathalia Lucca'),
 ('rafa@bridge.ufsc.br',3, 'Rafael Duarte' ),
 ('nathan@bridge.ufsc.br',3, 'Nathan Molinari'),
 ('davi@bridge.ufsc.br',3, 'Davi Morfim'),
 ('diogo@bridge.ufsc.br',3, 'Diogo de Souza'),
 ('juliana@bridge.ufsc.br',3, 'Juliana Pinheiro'),
 ('jades@bridge.ufsc.br',4, 'Jades Hammes'),
 ('suleiman@bridge.ufsc.br',4, 'João Suleiman' ),
 ('lucasrosaj@bridge.ufsc.br',4, 'Lucas da Rosa'),
 ('fabricio.matos@bridge.ufsc.br',4, 'Fabrício Matos'),
 ('caio@bridge.ufsc.br',4, 'Caio Pereira'),
 ('bruno@bridge.ufsc.br',4, 'Bruno Agostinho'),
 ('kanarek@bridge.ufsc.br',4, 'Guilherme Kanarek'),
 ('nathalia@bridge.ufsc.br',4, 'Nathalia Liz'),
 ('odilon@bridge.ufsc.br',4, 'Odilon Ferreira'),
 ('thaisgoulartf@bridge.ufsc.br',4, 'Thais Goulart'),
 ('mirian@bridge.ufsc.br',4, 'Mirian Pereira'),
 ('fabiosr@bridge.ufsc.br',4, 'Fabio Relbnitz'),
 ('taha@bridge.ufsc.br',4, 'Antonio Taha'),
 ('giselle.nascimento@bridge.ufsc.br',4, 'Giselle Nascimento'),
 ('cristiano@bridge.ufsc.br',4, 'Cristiano Franco'),
 ('postal@bridge.ufsc.br',4, 'Lucas Postal'),
 ('leo.soares@bridge.ufsc.br',4, 'Leonardo Soares');



insert into aluno (email, id_casa, nome) values
('mateus.batista@bridge.ufsc.br',5, 'Mateus Batista'),
('osvaldo@bridge.ufsc.br',5, 'Osvaldo da Rocha');