insert into casa values
(1, 'Grifinoria', 'Sua morada é a Grifinória; Casa onde habitam os corações indômitos; Ousadia e sangue-frio e nobreza Destacam os alunos da Grifinória dos demais.'),
(2, 'Lufa-Lufa', 'É na Lufa-Lufa que você vai morar; Onde seus moradores sãojustos e leais, Pacientes, sinceros, sem medo da dor.'),
(3, 'Corvinal', 'Será a velha e sábia Corvinal, A casa dos que tem a mente sempre alerta, Onde os homens de grande espírito e saber Sempre encontrarão companheiros seus iguais.'),
(4, 'Sonserina', 'A Sonserina será a sua casa; E ali fará seus verdadeiros amigos; Homens de astúcia que usam quaisquer meios para atingir os fins que antes colimaram.'),
(5, 'Professores', 'Nós, professores, somos muito bons em magia, sabe.');

insert into aluno (email, id_casa) values
 ('bruno.luiz@bridge.ufsc.br',1),
 ('giselle.nascimento@bridge.ufsc.br',1),
 ('leticia@bridge.ufsc.br',1),
 ('anna.victoria@bridge.ufsc.br',1),
 ('paulo@bridge.ufsc.br',1),
 ('burigo@bridge.ufsc.br',1),
 ('fabricio.matos@bridge.ufsc.br',1),
 ('leonardoschluter@bridge.ufsc.br',1),
 ('lucas.suppes@bridge.ufsc.br',1),
 ('kanarek@bridge.ufsc.br',1),
 ('chris@bridge.ufsc.br',1),
 ('monique@bridge.ufsc.br',1),
 ('rahony@bridge.ufsc.br',1),
 ('jobe@bridge.ufsc.br',1),
 ('gustavomoser@bridge.ufsc.br',1),
 ('odilon@bridge.ufsc.br',1),
 ('petroski@bridge.ufsc.br',1),
 ('lucas.joao@bridge.ufsc.br',1),
 ('nathan@bridge.ufsc.br',1),
 ('salomao@bridge.ufsc.br',2),
 ('nathalia@bridge.ufsc.br',2),
 ('allan@bridge.ufsc.br',2),
 ('luis.munoz@bridge.ufsc.br',2),
 ('lucasrosaj@bridge.ufsc.br',2),
 ('juliana@bridge.ufsc.br',2),
 ('ja.pierry@bridge.ufsc.br',2),
 ('leo.soares@bridge.ufsc.br',2),
 ('gustavolobo@bridge.ufsc.br',2),
 ('jades@bridge.ufsc.br',2),
 ('taha@bridge.ufsc.br',2),
 ('larissataw@bridge.ufsc.br',2),
 ('bruno@bridge.ufsc.br',2),
 ('caio@bridge.ufsc.br',2),
 ('leonardo.phildeg@bridge.ufsc.br',2),
 ('carlosrebelato@bridge.ufsc.br',2),
 ('diogo@bridge.ufsc.br',2),
 ('ricardo@bridge.ufsc.br',2),
 ('deborawernke@bridge.ufsc.br',3),
 ('delrobson@bridge.ufsc.br',3),
 ('gessica@bridge.ufsc.br',3),
 ('nathanwerlich@bridge.ufsc.br',3),
 ('candinho@bridge.ufsc.br',3),
 ('isaac@bridge.ufsc.br',3),
 ('thaisgoulartf@bridge.ufsc.br',3),
 ('isabellepinheiro@bridge.ufsc.br',3),
 ('mirian@bridge.ufsc.br',3),
 ('angelo@bridge.ufsc.br',3),
 ('suleiman@bridge.ufsc.br',3),
 ('celio@bridge.ufsc.br',3),
 ('jessica@bridge.ufsc.br',3),
 ('davi@bridge.ufsc.br',3),
 ('joaomiguel@bridge.ufsc.br',3),
 ('cristiano@bridge.ufsc.br',3),
 ('renan@bridge.ufsc.br',3),
 ('fernanda.mioto@bridge.ufsc.br',3),
 ('otavioribeiro@bridge.ufsc.br',3),
 ('postal@bridge.ufsc.br',4),
 ('ana.elisa@bridge.ufsc.br',4),
 ('nathalia.lucca@bridge.ufsc.br',4),
 ('marcel@bridge.ufsc.br',4),
 ('wag@bridge.ufsc.br',4),
 ('ewerton@bridge.ufsc.br',4),
 ('rafael@bridge.ufsc.br',4),
 ('fernando@bridge.ufsc.br',4),
 ('rafa@bridge.ufsc.br',4),
 ('camila@bridge.ufsc.br',4),
 ('saldanha@bridge.ufsc.br',4),
 ('amanda.aquino@bridge.ufsc.br',4),
 ('geovana@bridge.ufsc.br',4),
 ('christian@bridge.ufsc.br',4),
 ('fabiopreisler@bridge.ufsc.br',4),
 ('silvia@bridge.ufsc.br',4),
 ('fabiosr@bridge.ufsc.br',4);


insert into aluno (email, id_casa) values
('mateus.batista@bridge.ufsc.br',5),
('osvaldo@bridge.ufsc.br',5);